name: .NET

env:
  REPO_SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create Results Dir
      run: mkdir "/home/runner/work/dotnet-design-patterns/results"
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" -r "/home/runner/work/dotnet-design-patterns/results" --no-build --verbosity normal
    - name: Move results
      run: find /home/runner/work/dotnet-design-patterns/results -name "coverage.cobertura.xml" -exec mv -t /home/runner/work/dotnet-design-patterns/results {} +
    - name: List results
      run: ls /home/runner/work/dotnet-design-patterns/results
    - name: Clone repo
      run: git clone --single-branch --branch gh-page https://github.com/luizmotta01/dotnet-design-patterns.git /home/runner/work/dotnet-design-patterns/results/coveragereport
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.5.8
      with:
        reports: '/home/runner/work/dotnet-design-patterns/results/coverage.cobertura.xml'
        targetdir: '/home/runner/work/dotnet-design-patterns/results/coveragereport'
        reporttypes: Html
        assemblyfilters: '-xunit*'
    - uses: actions/checkout@v2
    - name: Push Reports
      run: |
          cd /home/runner/work/dotnet-design-patterns/results/coveragereport
          git config user.email "luizmotta01@hotmail.com"
          git config user.name "luizmotta01"
          git add .
          git commit -m "add reports"
          git push origin gh-page
      

