name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Remove Results Dir
      run: rm -rf "../results"
    - name: Create Results Dir
      run: mkdir "../results"
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" -r "/home/runner/work/dotnet-design-patterns/results" --no-build --verbosity normal
    - name: Go to results dir
      run: echo $(pwd) && cd "/home/runner/work/dotnet-design-patterns/results"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.5.8
      with:
        reports: $(pwd)'/'$(ls)'/coverage.cobertura.xml'
        targetdir: './coveragereport'
        reporttypes: Html
        assemblyfilters: '-xunit*'
