name: push analysis

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  analyze:
    needs: checkout
    uses: ./.github/workflows/analysis.yml
    with:
      pull-request: false
      branch-name: main
    secrets:
      sonar-url: ${{ secrets.SONAR_URL }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
