name: push

on:
  push:
    branches: [main]

jobs:
  sonar:
    uses: ./.github/workflows/sonar.yml
    with:
      pull-request: false
      branch-name: main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
