name: pull request analysis

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  sonar:
    needs: build
    uses: ./.github/workflows/sonar.yml
    with:
      pull-request: true
      pull-request-base: ${{ github.event.pull_request.base.ref }}
      pull-request-head: ${{ github.event.pull_request.head.ref }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
